export const ALLOWED_FOODS = {
  proteins: [
    "ovos",
    "peito de frango",
    "peru",
    "atum",
    "salmão",
    "carne de vaca",
    "carne de porco",
    "iogurte grego",
    "queijo fresco",
    "queijo cottage",
    "leite",
    "whey",
  ],
  carbs: [
    "arroz",
    "massa",
    "batata",
    "batata doce",
    "pão",
    "aveia",
    "banana",
    "maçã",
    "wrap",
    "tortilha",
    "granola",
  ],
  fats: [
    "azeite",
    "amêndoas",
    "nozes",
    "manteiga de amendoim",
    "abacate",
  ],
  veggies: [
    "alface",
    "tomate",
    "cenoura",
    "brócolos",
    "espinafres",
    "courgette",
    "pepino",
    "pimentos",
    "cebola",
  ],
};

export const FORBIDDEN_WORDS = [
  "algodão",
  "sabão",
  "detergente",
  "plástico",
  "papel",
  "shampoo",
  "desinfetante",
];
